### ISSUE TITLE
Dataset proposal: UniProt-Graphed

### ISSUE THREAD

**Issue by GaskaJanAllegro** [RiverBench/RiverBench#151]
### Description of the dataset

UniProt (Universal Protein Resource) is  high-quality, and freely accessible database of protein sequence and functional information. It integrates knowledge from various sources to provide annotations on protein functions, structures, and interactions (all in graph based style). The dataset includes:
      1. UniProtKB (Knowledgebase): Curated protein sequences with detailed annotations (over 220 million protein sequences).
      2. UniRef (Reference Clusters): Clusters of sequences to provide high coverage and reduce redundancy (around 470 million protein sequences).
      3. UniParc (Archive): Non-redundant repository of protein sequences from various sources (over 1.2 billion protein sequences).

### Value brought by the dataset

The dataset is extremely valuable for researchers in bioinformatics, molecular biology, and related fields. Its key benefits include:
    1. Coverage: Aggregates protein data from multiple sources, ensuring extensive coverage of known proteins.
    2. High-Quality Annotations: Curation by the experts ensures accurate functional information.
    3. Facilitates Research: Supports studies in protein function, structure, evolution, and interactions.
    4. Interoperability: Integrates seamlessly with other biological databases and tools, enhancing data utility.

### Proposed identifier

UniProt-Graphed

### Link to the source of the dataset

https://www.uniprot.org/help/downloads

### License of the dataset

https://creativecommons.org/licenses/by/4.0/

### Creator(s)

UniProt is the result of a collaborative effort among the following bioinformatics organizations:
    1. European Bioinformatics Institute (EBI): Part of the European Molecular Biology Laboratory (EMBL-EBI).
    2. Swiss Institute of Bioinformatics (SIB): Based in Switzerland, contributing to data curation and management.
    3. Protein Information Resource (PIR): An American organization focused on protein data integration.

### Stream type (according to RDF-STaX)

RDF dataset stream

### Stream element count

50

### How were the stream elements split

- Data Type:
-      UniProtKB (Knowledgebase): Divided into Reviewed (Swiss-Prot) and Unreviewed (TrEMBL) entries.
-      UniRef (Reference Clusters): Split into different cluster levels (UniRef100, UniRef90, UniRef50).
-      UniParc (Archive): Maintained as a comprehensive, non-redundant repository.

- Data Format:
  -   Available in multiple formats such as FASTA, XML, RDF, TXT, and others.
  -   Each format has its own set of download files to cater to diverse user requirements.

- Organism or Taxonomy:
  - For some datasets, especially within UniRef and UniProtKB, data may be partitioned based on specific organisms or taxonomic groups to allow focused analyses.

- Release Versions:
  - Data is organized based on release versions, ensuring that users can access historical data as well as the latest updates.

### Technical features

- [ ] Uses RDF-star
- [X] Uses generalized triples
- [X] Uses generalized datasets

### Additional technical notes (if any)

- Utilizes unique HTTP URIs for each protein entry and interlinks with semantic datasets like Bio2RDF and Wikidata.
- Incorporates ontologies such as Gene Ontology (GO) and Protein Ontology (PRO) using RDF Schema (RDFS) and OWL.
- Provides a publicly accessible and optimized SPARQL endpoint, enabling complex and federated queries for comprehensive data analysis.
- Implements automated validation pipelines to ensure schema compliance and data integrity, maintaining high-quality and reliable data.

### Metadata license

- [X] I agree to the terms

**Comment by Ostrzyciel** [comment]
Hi, thank you for the submission. However, this all seems to me very rushed, and, honestly, pretty much everything is filled in incorrectly, so there is not much to be discussed here.

Would like to maybe withdraw this submission, think this through, and then resubmit it again?

Please read the materials I gave you carefully, and put some work into this.

**Comment by Ostrzyciel** [comment]
Closing the issue doesn't delete it, don't worry :) yes, let's discuss it together.
